#!/usr/bin/env bash
# the project file layout is a template clone of http://www.davekuhlman.org/generateDS.html#id14
# for which we run:
git branch -D generated_odoo
git checkout -b generated_odoo

SCHEMA_NAME='nfe'
python quick_start.py --schema-name="$SCHEMA_NAME"
export GENERATEDS_HOME=${GENERATEDS_HOME:="/home/rvalyi/DEV/generateds"}

generate() {
  local version=$1
  local schemas_url=$2
  local lib_name="$SCHEMA_NAME"lib
  local gen_path="$SCHEMA_NAME"lib/"$version"
  wget -qO- --no-check-certificate "$schemas_url" -O /tmp/schemas.zip
  unzip /tmp/schemas.zip -d schemas/
  rm /tmp/schemas.zip
  unzip_path=$(ls schemas | head -n1)
  rm -rf "schemas/$version"
  mv schemas/"$unzip_path" "schemas/$version"
  rm -rf __init__.py

  local module_contents=$(cat  <<EOF
Module contents
=================

EOF
)

  echo "$module_contents" > docs/module_contents.txt
  echo "sys.path.append(os.path.abspath('../$gen_path'))" >> docs/conf.py

  rm -rf $gen_path
  mkdir -p $gen_path
  local odoo_path=odoo/models/"$version"
  mkdir -p $odoo_path
  touch "$lib_name"/__init__.py
  touch "$gen_path/__init__.py"

  cp "schemas/$version"/*.xsd "$GENERATEDS_HOME"/odoo

  for f in "schemas/$version"/leiaute*.xsd;
  do
    echo "Processing $f file..";
    local name=$(echo "$f" | sed 's/\.xsd//g' | sed 's/\./_/g' | sed "s/_$version//g")
    local module_name=$(echo $name | tr "/" "\n" | tail -n1)
    python3 "$GENERATEDS_HOME"/generateDS.py -o "$gen_path/$module_name".py "$f"
#    python3 "$GENERATEDS_HOME"/generateDS.py --member-specs="list" -o "$gen_path/$module_name".py "$f"
    autopep8 --in-place -p3 "$gen_path/$module_name".py

local current_dir=$(pwd)

    cd "$GENERATEDS_HOME"/odoo
    cp ../generateDS.py .
    local dotted_version=$(echo $version | sed 's/_/\./g')
    mv "$module_name"_"$dotted_version".xsd "$module_name"_"$version".xsd
    # avoids inclusion of signature elements in Python models:
    sed -i '/xmldsig-core-schema/d' "$module_name"_"$version".xsd
    # avoids the 'editix' prefix in generated XML:
    sed -i 's/xmlns:editix=\"http:\/\/www\.portalfiscal\.inf\.br\/nfe\"/xmlns:editix=\"http:\/\/www\.portalfiscal\.inf\.br\/editix\"/g' "$module_name"_"$version".xsd
    ./gends_run_gen_odoo.py -f -v "$module_name"_"$version".xsd
#    autopep8 --in-place -p3 models.py
    rm "$module_name"_"$version".py
    mv models.py "$current_dir/$odoo_path/$module_name".py

cd "$current_dir"

    module_name=$(echo $name | tr "/" "\n" | tail -n1)
    module_contents_part=$(cat  <<EOF
.. automodule:: $module_name
    :members:
    :undoc-members:
    :show-inheritance:
EOF
)
    echo "$module_contents_part" >> docs/module_contents.txt

  done
  rm -f "$GENERATEDS_HOME"/odoo/*.xsd
  rm -f "$GENERATEDS_HOME"/odoo/*lib.py
}

generate "v3_10" "http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=fXShsIS6w2Q="
generate "v4_00" "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=7PflO/zYa/0="


cd docs
make html
cd ..

rm -rf README.txt
rm -rf nfeutils.py
rm -rf sample_code

git add .
git commit . -m "classes and doc generated with ./generate"
